/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6jcVbHTAgLc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"
import { UserButton, ClerkLoading, ClerkLoaded } from "@clerk/nextjs"
import { NavigationMenu, NavigationMenuLink, NavigationMenuList } from "@/components/ui/navigation-menu"

export default function NavBar() {
  return (
    <header className="flex h-16 w-full items-center justify-between px-4 md:px-6 border-b">
      <div className="flex items-center gap-4">
        <NavigationMenu className="flex">
          <NavigationMenuList>
            <NavigationMenuLink href="/home" className="flex items-center gap-2 text-lg font-semibold">
              <BookIcon className="h-6 w-6" />
              <span>Spellbook</span>
            </NavigationMenuLink>
            <div className="w-8"></div> {/* Added spacing between Spellbook and My Classes */}
            <NavigationMenuLink href="/classes" className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50">
              My Classes
            </NavigationMenuLink>
            <NavigationMenuLink href="#" className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50">
              Insights
            </NavigationMenuLink>
            <NavigationMenuLink href="/quizzes" className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus:bg-gray-800 dark:focus:text-gray-50">
              Practice Quizzes
            </NavigationMenuLink>
          </NavigationMenuList>
        </NavigationMenu>
      </div>

      <ClerkLoaded>
        <UserButton />
      </ClerkLoaded>
      <ClerkLoading>
        <div className="animate-pulse flex space-x-4">
          <div className="rounded-full bg-gray-300 h-8 w-8"></div>
        </div>
      </ClerkLoading>
    </header>
  )
}

function BookIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}