FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y zip

COPY requirements.txt .
RUN pip install --target ./package -r requirements.txt

COPY lambda_function.py ./package/

RUN cd package && zip -r ../function.zip .