/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hrsRNL9yGlZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from 'react';  // Import useState from react

export function AddClassCard(props: { onSubmit: (name: string) => void }) {
  const [className, setClassName] = useState('');  // Initialize className state to an empty string

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setClassName(event.target.value);  // Set className to the value of the input field
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();  // Prevent the default form submission behavior
    props.onSubmit(className);  // Call the onSubmit prop with className
    setClassName('');  // Clear the className state after submission
  };

  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader>
        <CardTitle>Add New Class</CardTitle>
      </CardHeader>
      <CardContent>
        <form className="space-y-4" onSubmit={handleSubmit}>
          <div className="space-y-1">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter class name" value={className} onChange={handleInputChange} />
          </div>
          <Button className="w-full" type="submit">
            Add Class
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
